apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
  labels:
    app: world
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: world
          image: harbor.sysco-pcf.sysco.corby.cc/sof/world:latest

