apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
  labels:
    app: world
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: world
          image: harbor.sof-pilot.net/development/world:latest

